### ISSUE TITLE
Long maven project names cause rock build failures

### ISSUE THREAD

**Issue by pushkarnk** [rockcrafters/java-rockcraft-plugins#111]
### Bug Description

There is no hard limit on the length of the <name> attribute for a Maven project. However, names of rocks can have a maximum length of 40. 

Long project names cause failure at the `build-rock` and `build-build-rock` while running `rockcraft pack`.

### To Reproduce

This showed up while building [glassfish](https://github.com/eclipse-ee4j/glassfish) where the name of a module is:
```
<name>Code Quality Verification Tools - Configuration</name>
```

### Environment

N/A

### rockcraft.yaml

```yaml
summary: ''
name: build-code-quality-verification-tools-configuration
run-user: _daemon_
description: ''
version: 7.1.0-SNAPSHOT
build-base: ubuntu@24.04
platforms:
  amd64:
base: bare
....
....
```

### Relevant log output

```shell
Bad rockcraft.yaml content:
- string should have at most 40 characters (in field 'title')
For more information, check out: https://documentation.ubuntu.com/rockcraft/en/1.12.0/reference/rockcraft.yaml
```
